### ISSUE TITLE
"Execute Code" button not working when editing code

### ISSUE THREAD

**Issue by emregulcan** [jlattimer/CRMRESTBuilder#62] opened 2018-12-17 13:41 UTC
Hi,
I think this is part of issue #61 , when you modify created code inside "Code Editor", "Execute Code" button not working correctly.
Actually it does call to Web API but not show results on "Results" tab, when you open developer tools > network section, you can API endpoint and correct results.

Version 2.6.0.0
D365 online Version 1710 (9.1.0.996)

**Comment by MaxineHarwood** [comment] 2019-01-24 02:49
I've identified an issue and not sure if its related to yours as the consequences are the same. Are you using a filter of a picklist field?

 In my query I am retrieving multiple and using a filter to restrict records. one of my filter criteria is a picklist type. When i supply any value for the picklist and attempt to excecute, I get no results.

The issue is in the filter criteria generated. in my example the filter looks like this:
/api/data/v9.1/my_entity?$filter=my_picklistfield eq eq

note that the builder has the equals opertor listed twice, and does not insert the correct picklist value. in this instance the query should look like 
/api/data/v9.1/my_entity?$filter=my_picklistfield eq 200000

**Comment by emregulcan** [comment] 2019-01-24 20:16
Hi @MaxineHarwood ,
I think your issue exactly same with mine and others (#54 and #61 ). I'm sure this is simple bug (I didn't check the source code) and waiting some fixing for new release

**Comment by jlattimer** [comment] 2019-11-06 21:41
Was fixed in #76

**Closed by jlattimer** 2019-11-06 21:41 UTC
Labels: bug
